BATCH_SIZE: 128
CLASSES:
- Cherry
- Coffee-plant
- Cucumber
- Fox_nut(Makhana)
- Lemon
- Olive-tree
- Pearl_millet(bajra)
- Tobacco-plant
- almond
- banana
- cardamom
- chilli
- clove
- coconut
- cotton
- gram
- jowar
- jute
- maize
- mustard-oil
- papaya
- pineapple
- rice
- soyabean
- sugarcane
- sunflower
- tea
- tomato
- vigna-radiati(Mung)
- wheat
IMG_SIZE: 224
NORMALIZE_MEAN:
- 0.485
- 0.456
- 0.406
NORMALIZE_STD:
- 0.229
- 0.224
- 0.225
NUM_CLASSES: 30
